---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
library("COVID19")
library(tidyverse)
library(shiny)
library(shinydashboard)
library(shinyjs)
library(glue)
library(shinyWidgets)
library(plotly)
library(data.table)
library(highcharter)
library(shinycssloaders)
library(zoo)
```
```{r}
options(spinner.color="#0275D8", spinner.color.background="#ffffff", spinner.size=2)

```

```{r}
data <- covid19(raw=FALSE, verbose=FALSE)
glimpse(data)
```



```{r}
glimpse(data)
```
```{r}
abbr <- c(unique(data$id))
alias <- c(unique(data$administrative_area_level_1))
```

```{r}
names(abbr) <- alias
```
```{r}
abbr[1]
```


```{r}
subset_data <- data %>% filter(id=='CAN')
glimpse(subset_data)
```
```{r}
statistics <- list(
  "Daily cases" = "daily_cases_smoothed",
  "Daily deaths" = "daily_deaths_smoothed",
  "Daily tests" = "daily_tests_smoothed",
  "Hospital patients" = "hosp",
  "ICU patients" = "icu"
)
```


```{r}
restrictions <- c("school_closing", 
                  "workplace_closing", 
                  "cancel_events", 
                  "gatherings_restrictions", 
                  "transport_closing", 
                  "stay_home_restrictions", 
                  "internal_movement_restrictions", 
                  "international_movement_restrictions",
                  "information_campaigns", 
                  "testing_policy", 
                  "contact_tracing")
```

```{r}
school_closing_text <- list(
  "Open schools",
  "School closing recommended", 
  "School closing required (partial)", 
  "School closing required")
workplace_closing_text <- list(
  "Open workplaces",
  "Workplace closing recommended", 
  "Workplace closing required (partial)", 
  "Workplace closing required (non-essential)")
cancel_events_text <- list(
  "Events maintained",
  "Events cancelling recommended", 
  "Events cancelled")
gathering_restrictions_text <- list(
  "Gatherings allowed",
  "No gatherings above 1000 people",
  "No gathering above 100 people",
  "No gatherings above 10 people",
  "No gatherings (<10 people)")
transport_closing_text <- list(
  "Public transports maintained",
  "Public transports reduced",
  "Public transports closed")
stay_home_restrictions_text <- list(
  "No lockdown",
  "Staying home is recommended",
  "Lockdown (soft)",
  "Lockdown (hard)")
internal_movement_restrictions_text <- list(
  "No internal travel restriction",
  "Internal travel reduced",
  "Internal travel prohibited")
international_movement_restrictions_text <- list(
  "No international travel restriction",
  "Screening (International travel)",
  "High-risk regions quarantine (international)",
  "High-risk regions ban (international)",
  "Total border closure")
information_campaigns_text <- list(
  "No information campaign",
  "Information campaign",
  "Coordinated information campaign")
testing_policy_text <- list(
  "No testing policy",
  "Partial testing of symptomatic people",
  "Testing of symptomatic people",
  "Open public testing")
contact_tracing_text <- list(
  "No contact tracing",
  "Limited contact tracing",
  "Comprehensive contact tracing")
restrictions_categories=list(
  "Lockdown"=list("stay_home_restrictions"),
  "Travel&Transport"=list("international_movement_restrictions", 
                          "internal_movement_restrictions", 
                          "transport_closing"),
  "Schools&Workplaces"=list("school_closing", 
                            "workplace_closing"),
  "Information&Testing"=list("information_campaigns", 
                             "testing_policy", 
                             "contact_tracing"),
  "Events&Gatherings"=list("cancel_events", 
                           "gathering_restrictions")
)
restrictions_level_to_text <- list(
    "school_closing"=school_closing_text,
    "workplace_closing"=workplace_closing_text,
    "cancel_events"=cancel_events_text,
    "gathering_restrictions"=gathering_restrictions_text,
    "transport_closing"=transport_closing_text,
    "stay_home_restrictions"=stay_home_restrictions_text,
    "internal_movement_restrictions"=internal_movement_restrictions_text,
    "international_movement_restrictions"=international_movement_restrictions_text,
    "information_campaigns"=information_campaigns_text,
    "testing_policy"=testing_policy_text,
    "contact_tracing"=contact_tracing_text
)
colors = c("008000", "e6e6e6", "ffff66", "ff9900", "ff5050")
colors_name = c("green", "gray", "yellow", "orange", "red")
```

```{r}
all_data <- covid19(raw=FALSE, verbose=FALSE)
moving_average <- function(x, n = 7){round(stats::filter(x, rep(1 / n, n), sides = 1))}
```

```{r}
hc_theme_sparkline_vb <- function(...) {
    
    theme <- list(
        chart = list(
            backgroundColor = NULL,
            margins = c(0, 0, 0, 0),
            spacingTop = 0,
            spacingRight = 0,
            spacingBottom = 0,
            spacingLeft = 0,
            plotBorderWidth = 0,
            borderWidth = 0,
            style = list(overflow = "visible")
        ),
        xAxis = list(
            visible = FALSE, 
            endOnTick = FALSE, 
            startOnTick = FALSE
        ),
        yAxis = list(
            visible = FALSE,
            endOnTick = FALSE, 
            startOnTick = FALSE
        ),
        tooltip = list(
            outside = FALSE,
            shadow = FALSE,
            borderColor = "transparent",
            botderWidth = 0,
            backgroundColor = "transparent",
            style = list(textOutline = "5px white")
        ),
        plotOptions = list(
            series = list(
                marker = list(enabled = FALSE),
                lineWidth = 2,
                shadow = FALSE,
                fillOpacity = 0.25,
                color = "#FFFFFFBF",
                fillColor = list(
                    linearGradient = list(x1 = 0, y1 = 1, x2 = 0, y2 = 0),
                    stops = list(
                        list(0.00, "#FFFFFF00"),
                        list(0.50, "#FFFFFF7F"),
                        list(1.00, "#FFFFFFFF")
                    )
                )
            )
        ),
        credits = list(
            enabled = FALSE,
            text = ""
        )
    )
    
    theme <- structure(theme, class = "hc_theme")
    
    if (length(list(...)) > 0) {
        theme <- hc_theme_merge(
            theme,
            hc_theme(...)
        )
    }
    
    theme
}
valueBoxSpark <- function(value, title, sparkobj = NULL, subtitle, info = NULL, 
                          icon = NULL, color = "aqua", width = 4, href = NULL){
    
    shinydashboard:::validateColor(color)
    
    if (!is.null(icon))
        shinydashboard:::tagAssert(icon, type = "i")
    
    info_icon <- tags$small(
        tags$i(
            class = "fa fa-info-circle fa-lg",
            title = info,
            `data-toggle` = "tooltip",
            style = "color: rgba(255, 255, 255, 0.75);"
        ),
        # bs3 pull-right 
        # bs4 float-right
        class = "pull-right float-right"
    )
    
    boxContent <- div(
        class = paste0("small-box bg-", color),
        div(
            class = "inner",
            tags$small(title),
            if (!is.null(sparkobj)) info_icon,
            h3(value),
            if (!is.null(sparkobj)) sparkobj,
            p(subtitle)
        ),
        # bs3 icon-large
        # bs4 icon
        if (!is.null(icon)) div(class = "icon-large icon", icon, style = "z-index; 0")
    )
    
    if (!is.null(href)) 
        boxContent <- a(href = href, boxContent)
    
    div(
        class = if (!is.null(width)) paste0("col-sm-", width), 
        boxContent
    )
}
arrow <- function(num) {
    if(num < 0){
        return(HTML("&darr;"))
    }
    else if(num>0){ return(HTML("&uarr;")) }
    else return(HTML("-"))
}
```

```{r}
header <- dashboardHeader()
sidebar <- dashboardSidebar(
  collapsed = TRUE,
  sidebarMenu(),
  selectInput("country", "Select country",
              choices=abbr, selected="CAN"))
body <- dashboardBody(
  useShinyjs(),
  fluidPage(
    fluidRow(
      # withSpinner(valueBoxOutput("vbox1"), image = 'https://drive.google.com/u/0/uc?id=1YLP6tzIv6sB4pVYWQy9fRcUqAd8AYAEn'),
      valueBoxOutput("vbox1"),
      valueBoxOutput("vbox2"),
      valueBoxOutput("vbox3")
    ),
    fluidRow(
      div(
        id='mainplot',
        box(solidHeader = TRUE,
          status = "info",
          title = "Government measures over time",
          div(
            dropdownButton(
                tags$div(
                  style = "color: black !important;", # for text
                  h3("Plot options")
                ),
                selectInput(inputId = 'mainPlotY',
                            label = shiny::HTML("<p><span style='color: black'>Show evolution of</span></p>"),
                            selected = "Daily cases",
                            choices = names(statistics)),
                dateInput(inputId = 'mainPlotDate',
                          label = shiny::HTML("<p><span style='color: black'>See restrictions on</span></p>"),
                          value = max(all_data$date),
                          min = min(all_data$date),
                          max = max(all_data$date)),
                circle = FALSE,
                icon = icon("cog"),
                tooltip = tooltipOptions(title = "Click for plot options")
              ),
            class = "box-tools pull-right",
            id = "moveme1"
          ),
          plotOutput("main_plot")
        )
      ),
      box(solidHeader = TRUE,
        status = "info",
        title = "Measures in place at selected date",
        uiOutput("restrictions")
      )
    ),
    fluidRow(
      div(
        id='predictions',
        box(solidHeader = TRUE,
          status = "info",
          title = "Predictions",
          div(
            dropdownButton(
                tags$div(
                  style = "color: black !important;", # for text
                  h3("Plot options")
                ),
                dateInput("forecasting_start",
                  shiny::HTML("<p><span style='color: black'> Forecasting start date: </span></p>"),
                  min = min(all_data$date),
                  max = max(all_data$date),
                  value = as.Date(max(all_data$date))-30),
                sliderInput("forecasting_period",
                  shiny::HTML("<p><span style='color: black'>Forecasting range:</span></p>"),
                  min = 7,
                  max = 90,
                  value = 30),
                circle = FALSE,
                icon = icon("cog"),
                tooltip = tooltipOptions(title = "Click for plot options")
              ),
            class = "box-tools pull-right",
            id = "moveme2"
          ),
          plotOutput("forecasting")
        )
      ),
      uiOutput("forecast_box")
    )
  )
)
ui <- dashboardPage(header, sidebar, body)
```

```{r}
server <- function(input, output) {
  
    runjs("$('#mainplot .box-header').append($('#moveme1').detach())")
    runjs("$('#predictions .box-header').append($('#moveme2').detach())") 
  
    reactive_data <- reactive({filter(all_data, id==input$country) %>%
        mutate(daily_cases = confirmed - lag(confirmed, default=confirmed[1])) %>%
        mutate(daily_cases_smoothed = moving_average(daily_cases)) %>%
        mutate(daily_deaths = deaths - lag(deaths, default=deaths[1])) %>%
        mutate(daily_deaths_smoothed = moving_average(daily_deaths)) %>%
        mutate(daily_tests = tests - lag(tests, default=deaths[1])) %>%
        mutate(daily_tests_smoothed = moving_average(daily_tests))
    })
  
    output$vbox1 <- renderValueBox({
      data <- reactive_data()
      hc <- data  %>%
        hchart("line", hcaes(date, daily_cases_smoothed), name = "Cases Timeline")  %>%
        hc_size(height = 100) %>%
        hc_credits(enabled = FALSE) %>%
        hc_add_theme(hc_theme_sparkline_vb())
      total <- length(data$daily_cases_smoothed)
      today <- data$daily_cases_smoothed[total]
      week_back <- data$daily_cases_smoothed[total - 7]
      percent_week <- round((today - week_back)/week_back * 100)
      vb <- valueBoxSpark(
        value = round(today),
        title = toupper("Daily Cases"),
        sparkobj = hc,
        subtitle = tagList(arrow(percent_week), percent_week, "% Since last week"),
        info = "Daily number of COVID cases",
        width = 4,
        color = "teal",
        href = NULL
      )
      vb
    })
    output$vbox2 <- renderValueBox({
      data <- reactive_data()
      hc <- data  %>%
        hchart("line", hcaes(date, daily_deaths_smoothed), name = "Deaths Timeline")  %>%
        hc_size(height = 100) %>%
        hc_credits(enabled = FALSE) %>%
        hc_add_theme(hc_theme_sparkline_vb())
      total <- length(data$daily_deaths_smoothed)
      today <- data$daily_deaths_smoothed[total]
      week_back <- data$daily_deaths_smoothed[total - 7]
      percent_week <- round((today - week_back)/week_back * 100)
      vb <- valueBoxSpark(
        value = round(today),
        title = toupper("Daily Deaths"),
        sparkobj = hc,
        subtitle = tagList(arrow(percent_week), percent_week, "% Since last week"),
        info = "Daily number of COVID deaths",
        width = 4,
        color = "red",
        href = NULL
      )
      vb
    })
    output$vbox3 <- renderValueBox({
      data <- reactive_data()
      hc <- data  %>%
        hchart("line", hcaes(date, hosp), name = "Hospital Admissions Timeline")  %>%
        hc_size(height = 100) %>%
        hc_credits(enabled = FALSE) %>%
        hc_add_theme(hc_theme_sparkline_vb())
      total <- length(data$hosp)
      today <- data$hosp[total]
      week_back <- data$hosp[total - 7]
      percent_week <- round((today - week_back)/week_back * 100)
      vb <- valueBoxSpark(
        value = round(today),
        title = toupper("Hospital Admissions"),
        sparkobj = hc,
        subtitle = tagList(arrow(percent_week), percent_week, "% Since last week"),
        info = "Number of COVID patients in hospital beds",
        width = 4,
        color = "yellow",
        href = NULL
      )
      vb
    })
  
    output$main_plot <- renderPlot({
        data <- reactive_data()
        data <- data %>%
          mutate(to_show = data[[statistics[[input$mainPlotY]]]])
        
        if (!is.null(display_restriction())){
          levels = data[[display_restriction()]]+1
          colors_label = unlist(restrictions_level_to_text[[display_restriction()]], recursive=FALSE)
          breaks = as.character(1:length(colors_label))
          colors = head(colors_name, length(colors_label))
          names(colors) = breaks
          plot <- data %>%
            ggplot(aes(x=date, y=to_show, colour=factor(levels), 
                       group=c(0, cumsum(tail(levels != shift(levels, 1), -1))))) +
            geom_line(size=1.5) +
            scale_colour_manual(values=colors, breaks=breaks , labels=colors_label, 
                                name="Restrictions", drop=FALSE) +
            xlab("Date") + ylab(input$mainPlotY) +
            theme(legend.position="bottom",
                  legend.text=element_text(size=12),
                  axis.text=element_text(size=12),
                  axis.title=element_text(size=14))
        } else {
          plot <- data %>% 
            ggplot(aes(x=date, y=to_show)) +
            geom_line(size=1.5) +
            xlab("Date") + ylab("Daily cases") +
            theme(axis.text=element_text(size=12),
                  axis.title=element_text(size=14))
        }
        plot <- plot + 
          geom_vline(aes(xintercept=input$mainPlotDate), linetype = "dashed") +
          annotate("text", x=input$mainPlotDate, y = 0, label=input$mainPlotDate, hjust=1.2, vjust=1, color='black')
        return(plot)
    })
    
    output$restrictions <- renderUI({
        categories = tagList()
        data <- reactive_data()
        date_row = filter(data, date==input$mainPlotDate)
        i = 1
        for (cat in names(restrictions_categories)){
          buttons = tagList()
          j = 1
          for (name in restrictions_categories[[cat]]){
            level = date_row[[name]]
            if (!is.null(level)){
              buttons[[j]] = actionButton(
                glue("display_{name}"),
                restrictions_level_to_text[[name]][[level+1]],
                style=glue("color: #000; background-color: #{colors[[level+1]]}; border-color: #{colors[[level+1]]}")
              )
              j = j+1
            }
          }
          categories[[i]] = box(title=cat, buttons)
          i = i+1
        }
        categories
    })
    
    display_restriction <- reactiveVal(NULL)
    
    # Observe event for all buttons
    observe({
      input_btn <- paste0("display_", names(restrictions_level_to_text))
      lapply(input_btn,
             function(x){
               observeEvent(
                 input[[x]],
                 {
                   name <- sub("display_", "", x)
                   if (is.null(display_restriction()) || (display_restriction() != name)) {
                     display_restriction(name)
                   } else {
                     display_restriction(NULL)
                   }
                 }
               )
             }
      )
    })
    
    output$forecasting <- renderPlot({
        data <- reactive_data()
        # The date that you yant to choose, this date should be after 2020-03-01 to make good estimation 
        Re_start_date = input$forecasting_start
        Re_end_date = Re_start_date + input$forecasting_period
        max_date = max(data$date)
        # Use JRC method to estimate R number from historic data
        base_case = data %>% filter(date == Re_start_date) %>% pull(daily_cases_smoothed)
        old_case = data %>% filter(date == Re_start_date - 14) %>% pull(daily_cases_smoothed)
        R_number = exp((log(base_case) - log(old_case))/2)

        data = data %>%
          mutate(forecasting = ifelse(date < Re_start_date, 
              daily_cases_smoothed, 
              as.integer(base_case*(R_number**(as.numeric(date-Re_start_date)/7)))))
        if (Re_end_date <= max_date) { 
          plot_data <- data.frame(
            date = data$date,
            daily_cases_smoothed = data$daily_cases_smoothed,
            forecasting = ifelse(data$date < Re_start_date, 
              data$daily_cases_smoothed, 
              as.integer(base_case*(R_number**(as.numeric(data$date-Re_start_date)/7))))
          )
        } else {
          dates =  c(data$date, seq(max_date, Re_end_date, "days"))
          plot_data <- data.frame(
            date = dates,
            daily_cases_smoothed = c(data$daily_cases_smoothed, 
                                     rep(0, length(dates)-length(data$daily_cases_smoothed))),
            forecasting = ifelse(dates < Re_start_date, 
              c(data$daily_cases_smoothed, rep(0, length(dates)-length(data$daily_cases_smoothed))), 
              as.integer(base_case*(R_number**(as.numeric(dates-Re_start_date)/7))))
          )
        }
        plot = plot_data %>%
            ggplot(aes(x=date)) + 
            geom_line(aes(y=daily_cases_smoothed), size=1.5, filter(data, date < max_date)) +
            geom_line(aes(y=forecasting), color = "red", size=1.5, filter(plot_data, date < Re_end_date & date > Re_start_date)) +
            geom_vline(xintercept = as.numeric(as.Date(Re_start_date, format = "%Y-%m-%d")), colour = "black", linetype = 'dashed') + 
            annotate("text", x=Re_start_date, y = 0, label=Re_start_date, hjust=1.2, vjust=1, color='black') +
            theme(legend.position="none") + theme_bw() +
            xlab("Date") + ylab("Daily cases") +
            theme(axis.text=element_text(size=12),
                  axis.title=element_text(size=14))
        
        return(plot)
      
    })
    
    output$forecast_box <- renderUI({
        data <- reactive_data()
 
        Re_start_date = input$forecasting_start
        Re_end_date = Re_start_date + input$forecasting_period
        max_date = max(data$date)
        # Use JRC method to estimate R number from historic data
        base_case = data %>% filter(date == Re_start_date) %>% pull(daily_cases_smoothed)
        old_case = data %>% filter(date == Re_start_date - 14) %>% pull(daily_cases_smoothed)
        R_number = exp((log(base_case) - log(old_case))/2)
        
        # forecast 
        forecast_number = as.integer(base_case*(R_number**(input$forecasting_period/7)))
        if (Re_end_date <= max_date) {
          actual_number = data %>% filter(date == Re_end_date) %>% pull(daily_cases_smoothed)
          difference = actual_number - forecast_number
        } else {
          actual_number = "No data"
          difference = "No data"
        }
      
        list(
          infoBox(
          "R number", format(round(R_number, 2), nsmall = 2), icon = shiny::icon("bar-chart"),
          color = ifelse(R_number > 1, "orange", "green"), width = 6
          ),
          infoBox(
          "Forecasting cases", paste0(" ", forecast_number), icon = shiny::icon("bar-chart"),
          color = "red", width = 6
          ),
          infoBox(
          "Actual cases", paste0(" ", actual_number), icon = shiny::icon("bar-chart"),
          color = "black", width = 6
          ),
          infoBox(
          "Difference", paste0(" ", difference), icon = shiny::icon("bar-chart"),
          color = ifelse(difference > 0, "orange", "green"), width = 6
          )
        )
       
    })
    
}
```


```{r}
shinyApp(ui, server)
```




