---
title: "R Notebook"
output: html_notebook
---

# ```{r}
# library(ukcovid19)
# ```
# 
# ```{r}
# query_filters <- c(
#     'areaType=nation',
#     'areaName=England'
# )
# 
# request = list(
#     date = "date",
#     areaName = "areaName",
#     areaCode = "areaCode",
#     newCasesByPublishDate = "newCasesByPublishDate",
#     newDeaths28DaysByPublishDate = "newDeaths28DaysByPublishDate",
#     covidOccupiedMVBeds = "covidOccupiedMVBeds",
#     newAdmissions = "newAdmissions",
#     newTestsByPublishDate = "newTestsByPublishDate",
#     newPeopleVaccinatedFirstDoseByPublishDate = "newPeopleVaccinatedFirstDoseByPublishDate",
#     newPeopleVaccinatedSecondDoseByPublishDate = "newPeopleVaccinatedSecondDoseByPublishDate"
# )
# ```
# 
# ```{r}
# data <- get_data(
#     filters = query_filters, 
#     structure = request
# )
# data <- data %>% map_df(rev)
# 
# summary(data)
# ```
```{r}
library(tidyverse)
library(shiny)
library(shinydashboard)
```

```{r}
data <- read.csv("data/uk.csv")
glimpse(data)
max(data$date)
columns <- c("newCasesByPublishDate", "newDeaths28DaysByPublishDate", 
             "newTestsByPublishDate", "newAdmissions", 
             "hospitalCases", "covidOccupiedMVBeds")
```

```{r}
header <- dashboardHeader()

sidebar <- dashboardSidebar(
  collapsed = TRUE,
  sidebarMenu())

body <- dashboardBody(
  fluidRow(
    box(plotOutput("plot_cases")),
    
    box(
      selectInput("stat", "Select category", 
                  columns, selected=columns[1]),
      selectInput("event", "Select lockdown date", 
                  list("UK" = list("2021-01-04", "2020-03-23"))),
      sliderInput("duration", "Monitor effect for . days:", 7, 100, 60)
      # dateInput("date", "Date of lockdown", min=min(data$date), max=max(data$date)),
      # sliderInput("rolling_mean", "Rolling mean:", 1, 30, 7),
    )
  ),
  
  fluidRow(
    valueBoxOutput("evolution"),
  )
)

ui <- dashboardPage(header, sidebar, body)
```

```{r}
moving_average <- function(x, n = 7){stats::filter(x, rep(1 / n, n), sides = 1)}

server <- function(input, output) {
  
  output$plot_cases <- renderPlot({
    new_data <- data %>% mutate(smoothed = moving_average(data[input$stat], 7))
    ggplot(data=new_data, aes(x=as.Date(date))) +
      geom_line(aes_string(y=input$stat), alpha=0.3) +
      geom_line(aes(y=smoothed, colour='red'), size=1) +
      geom_area(aes(as.Date(date), y=smoothed), 
                data=subset(new_data, as.Date(date) >= as.Date(input$event) & 
                              as.Date(date) <= as.Date(input$event) + input$duration), 
                fill="green4", alpha=0.4) +
      xlab("Date") +
      ylab(paste("Number of ", columns[1])) +
      guides(color = FALSE)
  })
    
  output$evolution <- renderValueBox({
    new_data <- data %>% mutate(smoothed = moving_average(data[input$stat], 7))
    zoom <- drop_na(select(subset(new_data, as.Date(date) >= as.Date(input$event) & 
      as.Date(date) <= as.Date(input$event) + input$duration), input$stat))
    change <- zoom[nrow(zoom), input$stat] - zoom[1, input$stat]
    valueBox(
      change,
      paste(input$stat, "evolution"), 
      icon = icon(ifelse(change>=0, 'arrow-up', 'arrow-down')),
      color = ifelse(change>=0, 'red', 'green')
    )
  })
}

shinyApp(ui, server)
```

